spring:
  application:
    name: mall-enter
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true  #开启文件上传
      max-file-size: 10MB  #限制文件上传大小为10M
  main:
    allow-bean-definition-overriding: true  #EasyPoi启用覆盖
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #高版本SpringBoot2.7.0整合Swagger3问题，更改MVC路径匹配策略为AntPathMatcher
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
jwt:
  tokenHeader: Authorization  #JWT存储的请求头
  secret: mall-enter-secret  #JWT加解密使用的密钥
  expiration: 604800  #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '    #JWT负载中拿到开头

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

secure:
  ignored:
    urls:   #安全路径白名单
      - /doc.html
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /admin/**
      - /minio/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /menu/**
      - /order/**
      - /poi/**
      - /easyExcel/**
      - /easyPoi/**

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue

mongo:
  insert:
    sqlEnable: true # 用于控制是否通过数据库数据来插入mongo

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: test # 访问身份验证中用到用户标识
    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: macro-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀